### ISSUE TITLE
Hyper params used in 10x

### ISSUE THREAD

**Issue by alisadeghian** [facebookresearch/tkbc#1]
Hi, very interesting work!
Would you please share the hyper-params use in the 10x rank experiments (Table 6 in the paper)?

**Comment by timlacroix** [comment]
Hi. Thanks for the question. 
- For ICEWS05-15 : 
  - rank = 1280
  - emb_reg 1e-3
  - time_reg 5e-2
(leads to 0.67 in test)
- For  ICEWS14 :
  - rank = 1560
  - emb_reg 1e-2
  - time_reg 1e-2
(leads to 0.61 in test and 0.62 in valid, I'll re-run a grid-search to figure out whether I reported the wrong number in the paper...)
- For Yago15K:
  - rank = 1890
  - --no_time_emb
  - emb_reg 1e-2
  - time_reg 1
(leads to 0.36 in test)
