### ISSUE TITLE
why use reciprocal relations

### ISSUE THREAD

**Issue by JaneYul** [facebookresearch/tkbc#4]
Hi, I have a question on the code

`to_skip['lhs'][(rhs, rel + n_relations, ts)].add(lhs)  # reciprocals`
`to_skip['rhs'][(lhs, rel, ts)].add(rhs)`

It means that for each triple (s, p, o, t) in the dataset, add another inverse triple (s, p_reciprocal, o, t) in the corresponding dataset. Therefore, predicting (o, p_reciprocal, ?, t) is equivalent to predicting (?, p, o, t)?

**Comment by timlacroix** [comment]
The reason for this is explained in this paper :
https://arxiv.org/abs/1806.07297

**Comment by JaneYul** [comment]
Thanks!
