### ISSUE TITLE
How to reproduce the results of a tenfold increase of parameters?

### ISSUE THREAD

**Issue by yunzi-94** [facebookresearch/tkbc#5]
Your paper has reported the results of a tenfold increase of parameters, but how to reproduce it？ (I follow your readme.md to run the code, but can only get the results of the basic mode.)

**Comment by timlacroix** [comment]
The hyperparameters are given here : https://github.com/facebookresearch/tkbc/issues/1

**Comment by yunzi-94** [comment]
Thanks a lot. I will try it later.

**Comment by timlacroix** [comment]
In order to reproduce 62MRR for ICEWS14, contrary to what I answered in issue 1, use these parameters : 
```
python tkbc/learner.py --dataset ICEWS14 --model TNTComplEx --rank 1560 --emb_reg 5e-3 --time_reg 1e-2 --valid_freq 10 --max_epochs 100
```

**Comment by yunzi-94** [comment]
OK, thank you very much!
